Changes to address multiple issues
NOC-EO/seastar_project pull request #231
Opened 2023-02-02 16:43 UTC by DavidMcCann-NOC

2023-02-02 16:44 UTC, DavidMcCann-NOC commented
I've also added my environment.yml file for re-building the env. Notebooks were added to save to my branch before testing the rebasing problem at my end

2023-02-03 09:08 UTC, ACHMartin requested changes
ready to go after the modifications

2023-02-03 09:08 UTC, ACHMartin commented on env/environment.yml
> +  - xarray=2022.11.0
we should probably add `datetime` as well even if I think it is a dependence in `xarray`

2023-02-03 09:08 UTC, ACHMartin commented on seastar/oscar/level1.py
> +                    ds_dict[mid_id][var] = xr.DataArray(data=np.NaN)
much shorter version indeed :).
Do we need to specify line 40-42 the antennas (Fore, Aft, Mid)?

Line 49: should it be ds_dict[ANTENNA_2][var] = xr...Nan

2023-02-03 09:11 UTC, DavidMcCann-NOC commented on config.ini
> +oscar_path = D:\data\SEASTAR\SEASTARex\Data\Metasensing\OSCAR\
Ha! A typo on my system's folder name no less...thanks!

2023-02-03 09:11 UTC, DavidMcCann-NOC commented on env/environment.yml
> +  - xarray=2022.11.0
Good idea

2023-02-03 09:18 UTC, DavidMcCann-NOC commented on seastar/oscar/level1.py
> +                    ds_dict[mid_id][var] = xr.DataArray(data=np.NaN)
Good catch

2023-02-03 09:26 UTC, merged